# Generated by Django 4.1.5 on 2023-10-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255)),
                ('Position', models.CharField(blank=True, max_length=50)),
                ('Office', models.CharField(blank=True, max_length=50)),
                ('Age', models.IntegerField(default=0)),
                ('Start_Date', models.DateTimeField(verbose_name='%d/%m/%y')),
                ('Salary', models.IntegerField(default=0)),
            ],
        ),
    ]
